name: CI

on:
  push:
    branches: [ main ]

jobs: 
  test:
    env: 
      MY_SECRET: ${{secrets.CI_TEST}} 
      USER_NAME   : tomoyd
      USER_EMAIL  : ydh9419@163.com
      PUBLISH_DIR : ./dist
      GITHUB_REPOSITORY: show-ci
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install package
        run: yarn install

      - name: Git clone the repository
        run: |
          cd $PUBLISH_DIR
          git init
          git config --local user.email $USER_NAME
          git config --local user.name $USER_EMAIL
          git status
          git remote add origin https://$MY_SECRET@github.com/$GITHUB_REPOSITORY.git
          echo https://$MY_SECRET@github.com/$GITHUB_REPOSITORY.git
          git checkout -b gh-pages
          git add --all
          git commit -m "deploy to Github pages"
          git push origin gh-pages -f
          echo 🤘 deploy gh-pages complete.


       


